spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: eureka-server

eureka:
  instance:
    preferIpAddress: false
    hostname: eureka.com #eureka服务端的实例名称

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
